version: '3.8'

services:

  # Database service using MySQL image
  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: luiz
      MYSQL_PASSWORD: luiz123
    ports:
      - "3306:3306"

  # Backend service
  backend:
    build: . 
    container_name: ecommerce-backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env