version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: luiz
      MYSQL_PASSWORD: luiz-2024
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: ecommerce-app
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql-data:
