export const prodcuts = [
  {
    name: 'Maçã',
    description: 'Uma fruta vermelha doce.',
    path_image: null,
    delete: 0,
    price: 2.9,
    stock: 100,
    category_id: 1,
    seller_id: 1,
  },
  {
    name: 'Banana',
    description: 'Uma fruta amarela rica em potássio.',
    path_image: null,
    delete: 0,
    price: 1.5,
    stock: 150,
    category_id: 1,
    seller_id: 1,
  },
  {
    name: 'Suco de Laranja',
    description: 'Bebida refrescante de laranja.',
    path_image: null,
    delete: 0,
    price: 5.0,
    stock: 200,
    category_id: 1,
    seller_id: 1,
  },
  {
    name: 'Shampoo',
    description: 'Produto para lavar o cabelo.',
    path_image: null,
    delete: 0,
    price: 15.0,
    stock: 50,
    category_id: 2,
    seller_id: 1,
  },
  {
    name: 'Condicionador',
    description: 'Produto para amaciar o cabelo.',
    path_image: null,
    delete: 0,
    price: 12.0,
    stock: 50,
    category_id: 2,
    seller_id: 1,
  },
  {
    name: 'Sabonete',
    description: 'Sabonete perfumado para banho.',
    path_image: null,
    delete: 0,
    price: 2.5,
    stock: 200,
    category_id: 2,
    seller_id: 1,
  },
  {
    name: 'Detergente',
    description: 'Produto para lavar louças.',
    path_image: null,
    delete: 0,
    price: 3.0,
    stock: 100,
    category_id: 3,
    seller_id: 1,
  },
  {
    name: 'Desinfetante',
    description: 'Produto para desinfecção de superfícies.',
    path_image: null,
    delete: 0,
    price: 7.0,
    stock: 80,
    category_id: 3,
    seller_id: 1,
  },
  {
    name: 'Esponja de Limpeza',
    description: 'Esponja para lavar louças.',
    path_image: null,
    delete: 0,
    price: 1.0,
    stock: 150,
    category_id: 3,
    seller_id: 1,
  },
  {
    name: 'Smartphone',
    description: 'Aparelho celular moderno.',
    path_image: null,
    delete: 0,
    price: 1200.0,
    stock: 30,
    category_id: 4,
    seller_id: 1,
  },
  {
    name: 'Fone de Ouvido',
    description: 'Fone de ouvido sem fio.',
    path_image: null,
    delete: 0,
    price: 150.0,
    stock: 70,
    category_id: 4,
    seller_id: 1,
  },
  {
    name: 'Carregador',
    description: 'Carregador rápido para celular.',
    path_image: null,
    delete: 0,
    price: 50.0,
    stock: 100,
    category_id: 4,
    seller_id: 1,
  },
  {
    name: 'Camiseta',
    description: 'Camiseta de algodão.',
    path_image: null,
    delete: 0,
    price: 25.0,
    stock: 200,
    category_id: 5,
    seller_id: 1,
  },
  {
    name: 'Calça Jeans',
    description: 'Calça jeans azul.',
    path_image: null,
    delete: 0,
    price: 80.0,
    stock: 100,
    category_id: 5,
    seller_id: 1,
  },
  {
    name: 'Boné',
    description: 'Boné esportivo.',
    path_image: null,
    delete: 0,
    price: 20.0,
    stock: 50,
    category_id: 5,
    seller_id: 1,
  },
  {
    name: 'Boneca',
    description: 'Boneca para crianças.',
    path_image: null,
    delete: 0,
    price: 40.0,
    stock: 60,
    category_id: 6,
    seller_id: 1,
  },
  {
    name: 'Carrinho de Brinquedo',
    description: 'Carrinho de brinquedo para crianças.',
    path_image: null,
    delete: 0,
    price: 30.0,
    stock: 100,
    category_id: 6,
    seller_id: 1,
  },
  {
    name: 'Jogo de Tabuleiro',
    description: 'Jogo de tabuleiro divertido.',
    path_image: null,
    delete: 0,
    price: 50.0,
    stock: 40,
    category_id: 6,
    seller_id: 1,
  },
  {
    name: 'Caneta',
    description: 'Caneta esferográfica.',
    path_image: null,
    delete: 0,
    price: 2.0,
    stock: 500,
    category_id: 7,
    seller_id: 1,
  },
  {
    name: 'Caderno',
    description: 'Caderno de 100 folhas.',
    path_image: null,
    delete: 0,
    price: 10.0,
    stock: 300,
    category_id: 7,
    seller_id: 1,
  },
  {
    name: 'Lápis',
    description: 'Lápis de escrever.',
    path_image: null,
    delete: 0,
    price: 1.0,
    stock: 400,
    category_id: 7,
    seller_id: 1,
  },
  {
    name: 'Pneu',
    description: 'Pneu para carro.',
    path_image: null,
    delete: 0,
    price: 300.0,
    stock: 20,
    category_id: 8,
    seller_id: 1,
  },
  {
    name: 'Óleo de Motor',
    description: 'Óleo lubrificante para motor.',
    path_image: null,
    delete: 0,
    price: 40.0,
    stock: 50,
    category_id: 8,
    seller_id: 1,
  },
  {
    name: 'Bateria de Carro',
    description: 'Bateria automotiva.',
    path_image: null,
    delete: 0,
    price: 250.0,
    stock: 15,
    category_id: 8,
    seller_id: 1,
  },
  {
    name: 'Sofá',
    description: 'Sofá de 3 lugares.',
    path_image: null,
    delete: 0,
    price: 800.0,
    stock: 10,
    category_id: 9,
    seller_id: 1,
  },
  {
    name: 'Mesa de Jantar',
    description: 'Mesa de jantar com 6 cadeiras.',
    path_image: null,
    delete: 0,
    price: 1200.0,
    stock: 5,
    category_id: 9,
    seller_id: 1,
  },
  {
    name: 'Cadeira de Escritório',
    description: 'Cadeira ergonômica.',
    path_image: null,
    delete: 0,
    price: 500.0,
    stock: 20,
    category_id: 9,
    seller_id: 1,
  },
  {
    name: 'Tesoura de Poda',
    description: 'Tesoura para poda de plantas.',
    path_image: null,
    delete: 0,
    price: 25.0,
    stock: 60,
    category_id: 10,
    seller_id: 1,
  },
  {
    name: 'Regador',
    description: 'Regador de plástico.',
    path_image: null,
    delete: 0,
    price: 15.0,
    stock: 80,
    category_id: 10,
    seller_id: 1,
  },
  {
    name: 'Adubo',
    description: 'Adubo orgânico.',
    path_image: null,
    delete: 0,
    price: 30.0,
    stock: 100,
    category_id: 10,
    seller_id: 1,
  },
  {
    name: 'Ração para Cães',
    description: 'Ração seca para cães adultos.',
    path_image: null,
    delete: 0,
    price: 80.0,
    stock: 40,
    category_id: 11,
    seller_id: 1,
  },
  {
    name: 'Ração para Gatos',
    description: 'Ração seca para gatos adultos.',
    path_image: null,
    delete: 0,
    price: 70.0,
    stock: 50,
    category_id: 11,
    seller_id: 1,
  },
  {
    name: 'Brinquedo para Cães',
    description: 'Brinquedo de borracha para cães.',
    path_image: null,
    delete: 0,
    price: 20.0,
    stock: 100,
    category_id: 11,
    seller_id: 1,
  },
  {
    name: 'Martelo',
    description: 'Martelo de aço.',
    path_image: null,
    delete: 0,
    price: 25.0,
    stock: 60,
    category_id: 12,
    seller_id: 1,
  },
  {
    name: 'Furadeira',
    description: 'Furadeira elétrica.',
    path_image: null,
    delete: 0,
    price: 200.0,
    stock: 30,
    category_id: 12,
    seller_id: 1,
  },
  {
    name: 'Serra Elétrica',
    description: 'Serra elétrica para madeira.',
    path_image: null,
    delete: 0,
    price: 300.0,
    stock: 15,
    category_id: 12,
    seller_id: 1,
  },
  {
    name: 'Bola de Futebol',
    description: 'Bola oficial de futebol.',
    path_image: null,
    delete: 0,
    price: 100.0,
    stock: 50,
    category_id: 13,
    seller_id: 1,
  },
  {
    name: 'Raquete de Tênis',
    description: 'Raquete de tênis profissional.',
    path_image: null,
    delete: 0,
    price: 150.0,
    stock: 30,
    category_id: 13,
    seller_id: 1,
  },
  {
    name: 'Bicicleta',
    description: 'Bicicleta de montanha.',
    path_image: null,
    delete: 0,
    price: 800.0,
    stock: 20,
    category_id: 13,
    seller_id: 1,
  },
  {
    name: 'Laptop',
    description: 'Laptop com 16GB de RAM.',
    path_image: null,
    delete: 0,
    price: 3000.0,
    stock: 25,
    category_id: 14,
    seller_id: 1,
  },
  {
    name: 'Mouse',
    description: 'Mouse sem fio.',
    path_image: null,
    delete: 0,
    price: 80.0,
    stock: 100,
    category_id: 14,
    seller_id: 1,
  },
  {
    name: 'Teclado',
    description: 'Teclado mecânico.',
    path_image: null,
    delete: 0,
    price: 150.0,
    stock: 50,
    category_id: 14,
    seller_id: 1,
  },
  {
    name: 'Termômetro Digital',
    description: 'Termômetro digital para febre.',
    path_image: null,
    delete: 0,
    price: 40.0,
    stock: 80,
    category_id: 15,
    seller_id: 1,
  },
  {
    name: 'Medidor de Pressão',
    description: 'Medidor de pressão arterial.',
    path_image: null,
    delete: 0,
    price: 100.0,
    stock: 40,
    category_id: 15,
    seller_id: 1,
  },
  {
    name: 'Máscara Cirúrgica',
    description: 'Máscara descartável.',
    path_image: null,
    delete: 0,
    price: 1.0,
    stock: 1000,
    category_id: 15,
    seller_id: 1,
  },
  {
    name: 'Panela',
    description: 'Panela antiaderente.',
    path_image: null,
    delete: 0,
    price: 80.0,
    stock: 100,
    category_id: 16,
    seller_id: 1,
  },
  {
    name: 'Jogo de Talheres',
    description: 'Conjunto de talheres para 6 pessoas.',
    path_image: null,
    delete: 0,
    price: 50.0,
    stock: 150,
    category_id: 16,
    seller_id: 1,
  },
  {
    name: 'Liquidificador',
    description: 'Liquidificador potente.',
    path_image: null,
    delete: 0,
    price: 150.0,
    stock: 40,
    category_id: 16,
    seller_id: 1,
  },
  {
    name: 'Tênis Esportivo',
    description: 'Tênis para corrida.',
    path_image: null,
    delete: 0,
    price: 200.0,
    stock: 80,
    category_id: 17,
    seller_id: 1,
  },
  {
    name: 'Sandália',
    description: 'Sandália confortável.',
    path_image: null,
    delete: 0,
    price: 50.0,
    stock: 120,
    category_id: 17,
    seller_id: 1,
  },
  {
    name: 'Bota',
    description: 'Bota de couro.',
    path_image: null,
    delete: 0,
    price: 300.0,
    stock: 50,
    category_id: 17,
    seller_id: 1,
  },
  {
    name: 'Body para Bebê',
    description: 'Body de algodão para bebês.',
    path_image: null,
    delete: 0,
    price: 30.0,
    stock: 100,
    category_id: 18,
    seller_id: 1,
  },
  {
    name: 'Mamadeira',
    description: 'Mamadeira anti-cólica.',
    path_image: null,
    delete: 0,
    price: 25.0,
    stock: 150,
    category_id: 18,
    seller_id: 1,
  },
  {
    name: 'Carrinho de Bebê',
    description: 'Carrinho de bebê confortável.',
    path_image: null,
    delete: 0,
    price: 500.0,
    stock: 20,
    category_id: 18,
    seller_id: 1,
  },
  {
    name: 'Romance Clássico',
    description: 'Livro de romance clássico.',
    path_image: null,
    delete: 0,
    price: 35.0,
    stock: 200,
    category_id: 19,
    seller_id: 1,
  },
  {
    name: 'Revista de Moda',
    description: 'Revista mensal sobre moda.',
    path_image: null,
    delete: 0,
    price: 10.0,
    stock: 300,
    category_id: 19,
    seller_id: 1,
  },
  {
    name: 'Quadrinho',
    description: 'Quadrinho para crianças.',
    path_image: null,
    delete: 0,
    price: 15.0,
    stock: 150,
    category_id: 19,
    seller_id: 1,
  },
  {
    name: 'Vaso Decorativo',
    description: 'Vaso de cerâmica decorativo.',
    path_image: null,
    delete: 0,
    price: 80.0,
    stock: 50,
    category_id: 20,
    seller_id: 1,
  },
  {
    name: 'Quadro',
    description: 'Quadro de parede.',
    path_image: null,
    delete: 0,
    price: 150.0,
    stock: 40,
    category_id: 20,
    seller_id: 1,
  },
  {
    name: 'Luminária',
    description: 'Luminária de mesa.',
    path_image: null,
    delete: 0,
    price: 60.0,
    stock: 80,
    category_id: 20,
    seller_id: 1,
  },
  {
    name: 'Suco de Uva',
    description: 'Bebida refrescante de uva.',
    path_image: null,
    delete: 0,
    price: 6.0,
    stock: 100,
    category_id: 1,
    seller_id: 1,
  },
  {
    name: 'Água Mineral',
    description: 'Água mineral natural.',
    path_image: null,
    delete: 0,
    price: 1.5,
    stock: 200,
    category_id: 1,
    seller_id: 1,
  },
  {
    name: 'Biscoito de Chocolate',
    description: 'Biscoito recheado com chocolate.',
    path_image: null,
    delete: 0,
    price: 4.0,
    stock: 150,
    category_id: 1,
    seller_id: 1,
  },
  {
    name: 'Sabonete Líquido',
    description: 'Sabonete líquido para mãos.',
    path_image: null,
    delete: 0,
    price: 10.0,
    stock: 120,
    category_id: 2,
    seller_id: 1,
  },
  {
    name: 'Creme Hidratante',
    description: 'Creme hidratante para a pele.',
    path_image: null,
    delete: 0,
    price: 20.0,
    stock: 60,
    category_id: 2,
    seller_id: 1,
  },
  {
    name: 'Desodorante',
    description: 'Desodorante aerosol.',
    path_image: null,
    delete: 0,
    price: 15.0,
    stock: 80,
    category_id: 2,
    seller_id: 1,
  },
  {
    name: 'Água Sanitária',
    description: 'Produto para desinfecção de roupas e superfícies.',
    path_image: null,
    delete: 0,
    price: 3.5,
    stock: 200,
    category_id: 3,
    seller_id: 1,
  },
  {
    name: 'Limpa Vidros',
    description: 'Produto para limpeza de vidros.',
    path_image: null,
    delete: 0,
    price: 5.0,
    stock: 100,
    category_id: 3,
    seller_id: 1,
  },
  {
    name: 'Sabão em Pó',
    description: 'Sabão em pó para lavar roupas.',
    path_image: null,
    delete: 0,
    price: 12.0,
    stock: 80,
    category_id: 3,
    seller_id: 1,
  },
  {
    name: 'Televisão',
    description: 'Televisão LED 42 polegadas.',
    path_image: null,
    delete: 0,
    price: 2000.0,
    stock: 20,
    category_id: 4,
    seller_id: 1,
  },
  {
    name: 'Tablet',
    description: 'Tablet com tela de 10 polegadas.',
    path_image: null,
    delete: 0,
    price: 1500.0,
    stock: 25,
    category_id: 4,
    seller_id: 1,
  },
  {
    name: 'Smartphone',
    description: 'Smartphone com câmera de 48MP.',
    path_image: null,
    delete: 0,
    price: 2500.0,
    stock: 30,
    category_id: 4,
    seller_id: 1,
  },
  {
    name: 'Camiseta',
    description: 'Camiseta 100% algodão.',
    path_image: null,
    delete: 0,
    price: 50.0,
    stock: 100,
    category_id: 5,
    seller_id: 1,
  },
  {
    name: 'Calça Jeans',
    description: 'Calça jeans masculina.',
    path_image: null,
    delete: 0,
    price: 100.0,
    stock: 80,
    category_id: 5,
    seller_id: 1,
  },
  {
    name: 'Boné',
    description: 'Boné ajustável.',
    path_image: null,
    delete: 0,
    price: 30.0,
    stock: 120,
    category_id: 5,
    seller_id: 1,
  },
  {
    name: 'Boneca',
    description: 'Boneca de pano.',
    path_image: null,
    delete: 0,
    price: 40.0,
    stock: 100,
    category_id: 6,
    seller_id: 1,
  },
  {
    name: 'Carrinho de Brinquedo',
    description: 'Carrinho de brinquedo de metal.',
    path_image: null,
    delete: 0,
    price: 25.0,
    stock: 150,
    category_id: 6,
    seller_id: 1,
  },
  {
    name: 'Quebra-Cabeça',
    description: 'Quebra-cabeça de 1000 peças.',
    path_image: null,
    delete: 0,
    price: 50.0,
    stock: 60,
    category_id: 6,
    seller_id: 1,
  },
  {
    name: 'Caderno',
    description: 'Caderno universitário.',
    path_image: null,
    delete: 0,
    price: 20.0,
    stock: 200,
    category_id: 7,
    seller_id: 1,
  },
  {
    name: 'Caneta',
    description: 'Caneta esferográfica azul.',
    path_image: null,
    delete: 0,
    price: 2.0,
    stock: 300,
    category_id: 7,
    seller_id: 1,
  },
  {
    name: 'Mochila Escolar',
    description: 'Mochila para estudantes.',
    path_image: null,
    delete: 0,
    price: 80.0,
    stock: 50,
    category_id: 7,
    seller_id: 1,
  },
  {
    name: 'Pneu',
    description: 'Pneu para carro.',
    path_image: null,
    delete: 0,
    price: 300.0,
    stock: 50,
    category_id: 8,
    seller_id: 1,
  },
  {
    name: 'Óleo de Motor',
    description: 'Óleo lubrificante para motor.',
    path_image: null,
    delete: 0,
    price: 30.0,
    stock: 100,
    category_id: 8,
    seller_id: 1,
  },
  {
    name: 'Bateria de Carro',
    description: 'Bateria de carro 60Ah.',
    path_image: null,
    delete: 0,
    price: 400.0,
    stock: 30,
    category_id: 8,
    seller_id: 1,
  },
  {
    name: 'Sofá',
    description: 'Sofá de 3 lugares.',
    path_image: null,
    delete: 0,
    price: 1500.0,
    stock: 20,
    category_id: 9,
    seller_id: 1,
  },
  {
    name: 'Mesa de Jantar',
    description: 'Mesa de jantar para 6 pessoas.',
    path_image: null,
    delete: 0,
    price: 1000.0,
    stock: 15,
    category_id: 9,
    seller_id: 1,
  },
  {
    name: 'Cadeira de Escritório',
    description: 'Cadeira ergonômica para escritório.',
    path_image: null,
    delete: 0,
    price: 600.0,
    stock: 25,
    category_id: 9,
    seller_id: 1,
  },
  {
    name: 'Pá de Jardim',
    description: 'Pá de metal para jardinagem.',
    path_image: null,
    delete: 0,
    price: 25.0,
    stock: 50,
    category_id: 10,
    seller_id: 1,
  },
  {
    name: 'Vaso de Planta',
    description: 'Vaso de plástico para plantas.',
    path_image: null,
    delete: 0,
    price: 15.0,
    stock: 80,
    category_id: 10,
    seller_id: 1,
  },
  {
    name: 'Mangueira',
    description: 'Mangueira de jardim 20 metros.',
    path_image: null,
    delete: 0,
    price: 50.0,
    stock: 40,
    category_id: 10,
    seller_id: 1,
  },
  {
    name: 'Ração para Cães',
    description: 'Ração premium para cães adultos.',
    path_image: null,
    delete: 0,
    price: 120.0,
    stock: 100,
    category_id: 11,
    seller_id: 1,
  },
  {
    name: 'Brinquedo para Gatos',
    description: 'Brinquedo interativo para gatos.',
    path_image: null,
    delete: 0,
    price: 30.0,
    stock: 150,
    category_id: 11,
    seller_id: 1,
  },
  {
    name: 'Caixa de Transporte',
    description: 'Caixa de transporte para pets.',
    path_image: null,
    delete: 0,
    price: 150.0,
    stock: 60,
    category_id: 11,
    seller_id: 1,
  },
];
