export const prodcuts = [
  [
    {
      name: 'Maçã',
      description: 'Uma fruta vermelha doce.',
      price: 2.9,
      stock: 100,
      category_id: 1,
      seller_id: 1,
    },
    {
      name: 'Banana',
      description: 'Uma fruta amarela rica em potássio.',
      price: 1.5,
      stock: 150,
      category_id: 1,
      seller_id: 1,
    },
    {
      name: 'Suco de Laranja',
      description: 'Bebida refrescante de laranja.',
      price: 5.0,
      stock: 200,
      category_id: 1,
      seller_id: 1,
    },
    {
      name: 'Shampoo',
      description: 'Produto para lavar o cabelo.',
      price: 15.0,
      stock: 50,
      category_id: 2,
      seller_id: 1,
    },
    {
      name: 'Condicionador',
      description: 'Produto para amaciar o cabelo.',
      price: 12.0,
      stock: 50,
      category_id: 2,
      seller_id: 1,
    },
    {
      name: 'Sabonete',
      description: 'Sabonete perfumado para banho.',
      price: 2.5,
      stock: 200,
      category_id: 2,
      seller_id: 1,
    },
    {
      name: 'Detergente',
      description: 'Produto para lavar louças.',
      price: 3.0,
      stock: 100,
      category_id: 3,
      seller_id: 1,
    },
    {
      name: 'Desinfetante',
      description: 'Produto para desinfecção de superfícies.',
      price: 7.0,
      stock: 80,
      category_id: 3,
      seller_id: 1,
    },
    {
      name: 'Esponja de Limpeza',
      description: 'Esponja para lavar louças.',
      price: 1.0,
      stock: 150,
      category_id: 3,
      seller_id: 1,
    },
    {
      name: 'Smartphone',
      description: 'Aparelho celular moderno.',
      price: 1200.0,
      stock: 30,
      category_id: 4,
      seller_id: 1,
    },
    {
      name: 'Fone de Ouvido',
      description: 'Fone de ouvido sem fio.',
      price: 150.0,
      stock: 70,
      category_id: 4,
      seller_id: 1,
    },
    {
      name: 'Carregador',
      description: 'Carregador rápido para celular.',
      price: 50.0,
      stock: 100,
      category_id: 4,
      seller_id: 1,
    },
    {
      name: 'Camiseta',
      description: 'Camiseta de algodão.',
      price: 25.0,
      stock: 200,
      category_id: 5,
      seller_id: 1,
    },
    {
      name: 'Calça Jeans',
      description: 'Calça jeans azul.',
      price: 80.0,
      stock: 100,
      category_id: 5,
      seller_id: 1,
    },
    {
      name: 'Boné',
      description: 'Boné esportivo.',
      price: 20.0,
      stock: 50,
      category_id: 5,
      seller_id: 1,
    },
    {
      name: 'Boneca',
      description: 'Boneca para crianças.',
      price: 40.0,
      stock: 60,
      category_id: 6,
      seller_id: 1,
    },
    {
      name: 'Carrinho de Brinquedo',
      description: 'Carrinho de brinquedo para crianças.',
      price: 30.0,
      stock: 100,
      category_id: 6,
      seller_id: 1,
    },
    {
      name: 'Jogo de Tabuleiro',
      description: 'Jogo de tabuleiro divertido.',
      price: 50.0,
      stock: 40,
      category_id: 6,
      seller_id: 1,
    },
    {
      name: 'Caneta',
      description: 'Caneta esferográfica.',
      price: 2.0,
      stock: 500,
      category_id: 7,
      seller_id: 1,
    },
    {
      name: 'Caderno',
      description: 'Caderno de 100 folhas.',
      price: 10.0,
      stock: 300,
      category_id: 7,
      seller_id: 1,
    },
    {
      name: 'Lápis',
      description: 'Lápis de escrever.',
      price: 1.0,
      stock: 400,
      category_id: 7,
      seller_id: 1,
    },
    {
      name: 'Pneu',
      description: 'Pneu para carro.',
      price: 300.0,
      stock: 20,
      category_id: 8,
      seller_id: 1,
    },
    {
      name: 'Óleo de Motor',
      description: 'Óleo lubrificante para motor.',
      price: 40.0,
      stock: 50,
      category_id: 8,
      seller_id: 1,
    },
    {
      name: 'Bateria de Carro',
      description: 'Bateria automotiva.',
      price: 250.0,
      stock: 15,
      category_id: 8,
      seller_id: 1,
    },
    {
      name: 'Sofá',
      description: 'Sofá de 3 lugares.',
      price: 800.0,
      stock: 10,
      category_id: 9,
      seller_id: 1,
    },
    {
      name: 'Mesa de Jantar',
      description: 'Mesa de jantar com 6 cadeiras.',
      price: 1200.0,
      stock: 5,
      category_id: 9,
      seller_id: 1,
    },
    {
      name: 'Cadeira de Escritório',
      description: 'Cadeira ergonômica.',
      price: 500.0,
      stock: 20,
      category_id: 9,
      seller_id: 1,
    },
    {
      name: 'Tesoura de Poda',
      description: 'Tesoura para poda de plantas.',
      price: 25.0,
      stock: 60,
      category_id: 10,
      seller_id: 1,
    },
    {
      name: 'Regador',
      description: 'Regador de plástico.',
      price: 15.0,
      stock: 80,
      category_id: 10,
      seller_id: 1,
    },
    {
      name: 'Adubo',
      description: 'Adubo orgânico.',
      price: 30.0,
      stock: 100,
      category_id: 10,
      seller_id: 1,
    },
    {
      name: 'Ração para Cães',
      description: 'Ração seca para cães adultos.',
      price: 80.0,
      stock: 40,
      category_id: 11,
      seller_id: 1,
    },
    {
      name: 'Ração para Gatos',
      description: 'Ração seca para gatos adultos.',
      price: 70.0,
      stock: 50,
      category_id: 11,
      seller_id: 1,
    },
    {
      name: 'Brinquedo para Cães',
      description: 'Brinquedo de borracha para cães.',
      price: 20.0,
      stock: 100,
      category_id: 11,
      seller_id: 1,
    },
    {
      name: 'Martelo',
      description: 'Martelo de aço.',
      price: 25.0,
      stock: 60,
      category_id: 12,
      seller_id: 1,
    },
    {
      name: 'Furadeira',
      description: 'Furadeira elétrica.',
      price: 200.0,
      stock: 30,
      category_id: 12,
      seller_id: 1,
    },
    {
      name: 'Serra Elétrica',
      description: 'Serra elétrica para madeira.',
      price: 300.0,
      stock: 15,
      category_id: 12,
      seller_id: 1,
    },
    {
      name: 'Bola de Futebol',
      description: 'Bola oficial de futebol.',
      price: 100.0,
      stock: 50,
      category_id: 13,
      seller_id: 1,
    },
    {
      name: 'Raquete de Tênis',
      description: 'Raquete de tênis profissional.',
      price: 150.0,
      stock: 30,
      category_id: 13,
      seller_id: 1,
    },
    {
      name: 'Bicicleta',
      description: 'Bicicleta de montanha.',
      price: 800.0,
      stock: 20,
      category_id: 13,
      seller_id: 1,
    },
    {
      name: 'Laptop',
      description: 'Laptop com 16GB de RAM.',
      price: 3000.0,
      stock: 25,
      category_id: 14,
      seller_id: 1,
    },
    {
      name: 'Mouse',
      description: 'Mouse sem fio.',
      price: 80.0,
      stock: 100,
      category_id: 14,
      seller_id: 1,
    },
    {
      name: 'Teclado',
      description: 'Teclado mecânico.',
      price: 150.0,
      stock: 50,
      category_id: 14,
      seller_id: 1,
    },
    {
      name: 'Termômetro Digital',
      description: 'Termômetro digital para febre.',
      price: 40.0,
      stock: 80,
      category_id: 15,
      seller_id: 1,
    },
    {
      name: 'Medidor de Pressão',
      description: 'Medidor de pressão arterial.',
      price: 100.0,
      stock: 40,
      category_id: 15,
      seller_id: 1,
    },
    {
      name: 'Máscara Cirúrgica',
      description: 'Máscara descartável.',
      price: 1.0,
      stock: 1000,
      category_id: 15,
      seller_id: 1,
    },
    {
      name: 'Panela',
      description: 'Panela antiaderente.',
      price: 80.0,
      stock: 100,
      category_id: 16,
      seller_id: 1,
    },
    {
      name: 'Jogo de Talheres',
      description: 'Conjunto de talheres para 6 pessoas.',
      price: 50.0,
      stock: 150,
      category_id: 16,
      seller_id: 1,
    },
    {
      name: 'Liquidificador',
      description: 'Liquidificador potente.',
      price: 150.0,
      stock: 40,
      category_id: 16,
      seller_id: 1,
    },
    {
      name: 'Tênis Esportivo',
      description: 'Tênis para corrida.',
      price: 200.0,
      stock: 80,
      category_id: 17,
      seller_id: 1,
    },
    {
      name: 'Sandália',
      description: 'Sandália confortável.',
      price: 50.0,
      stock: 120,
      category_id: 17,
      seller_id: 1,
    },
    {
      name: 'Bota',
      description: 'Bota de couro.',
      price: 300.0,
      stock: 50,
      category_id: 17,
      seller_id: 1,
    },
    {
      name: 'Body para Bebê',
      description: 'Body de algodão para bebês.',
      price: 30.0,
      stock: 100,
      category_id: 18,
      seller_id: 1,
    },
    {
      name: 'Mamadeira',
      description: 'Mamadeira anti-cólica.',
      price: 25.0,
      stock: 150,
      category_id: 18,
      seller_id: 1,
    },
    {
      name: 'Carrinho de Bebê',
      description: 'Carrinho de bebê confortável.',
      price: 500.0,
      stock: 20,
      category_id: 18,
      seller_id: 1,
    },
    {
      name: 'Romance Clássico',
      description: 'Livro de romance clássico.',
      price: 35.0,
      stock: 200,
      category_id: 19,
      seller_id: 1,
    },
    {
      name: 'Revista de Moda',
      description: 'Revista mensal sobre moda.',
      price: 10.0,
      stock: 300,
      category_id: 19,
      seller_id: 1,
    },
    {
      name: 'Quadrinho',
      description: 'Quadrinho para crianças.',
      price: 15.0,
      stock: 150,
      category_id: 19,
      seller_id: 1,
    },
    {
      name: 'Vaso Decorativo',
      description: 'Vaso de cerâmica decorativo.',
      price: 80.0,
      stock: 50,
      category_id: 20,
      seller_id: 1,
    },
    {
      name: 'Quadro',
      description: 'Quadro de parede.',
      price: 150.0,
      stock: 40,
      category_id: 20,
      seller_id: 1,
    },
    {
      name: 'Luminária',
      description: 'Luminária de mesa.',
      price: 60.0,
      stock: 80,
      category_id: 20,
      seller_id: 1,
    },
    {
      name: 'Suco de Uva',
      description: 'Bebida refrescante de uva.',
      price: 6.0,
      stock: 100,
      category_id: 1,
      seller_id: 1,
    },
    {
      name: 'Água Mineral',
      description: 'Água mineral natural.',
      price: 1.5,
      stock: 200,
      category_id: 1,
      seller_id: 1,
    },
    {
      name: 'Biscoito de Chocolate',
      description: 'Biscoito recheado com chocolate.',
      price: 4.0,
      stock: 150,
      category_id: 1,
      seller_id: 1,
    },
    {
      name: 'Sabonete Líquido',
      description: 'Sabonete líquido para mãos.',
      price: 10.0,
      stock: 120,
      category_id: 2,
      seller_id: 1,
    },
    {
      name: 'Creme Hidratante',
      description: 'Creme hidratante para a pele.',
      price: 20.0,
      stock: 60,
      category_id: 2,
      seller_id: 1,
    },
    {
      name: 'Desodorante',
      description: 'Desodorante aerosol.',
      price: 15.0,
      stock: 80,
      category_id: 2,
      seller_id: 1,
    },
    {
      name: 'Água Sanitária',
      description: 'Produto para desinfecção de roupas e superfícies.',
      price: 3.5,
      stock: 200,
      category_id: 3,
      seller_id: 1,
    },
    {
      name: 'Limpa Vidros',
      description: 'Produto para limpeza de vidros.',
      price: 5.0,
      stock: 100,
      category_id: 3,
      seller_id: 1,
    },
    {
      name: 'Sabão em Pó',
      description: 'Sabão em pó para lavar roupas.',
      price: 12.0,
      stock: 80,
      category_id: 3,
      seller_id: 1,
    },
    {
      name: 'Televisão',
      description: 'Televisão LED 42 polegadas.',
      price: 2000.0,
      stock: 20,
      category_id: 4,
      seller_id: 1,
    },
    {
      name: 'Tablet',
      description: 'Tablet com tela de 10 polegadas.',
      price: 1500.0,
      stock: 25,
      category_id: 4,
      seller_id: 1,
    },
    {
      name: 'Smartphone',
      description: 'Smartphone com câmera de 48MP.',
      price: 2500.0,
      stock: 30,
      category_id: 4,
      seller_id: 1,
    },
    {
      name: 'Camiseta',
      description: 'Camiseta 100% algodão.',
      price: 50.0,
      stock: 100,
      category_id: 5,
      seller_id: 1,
    },
    {
      name: 'Calça Jeans',
      description: 'Calça jeans masculina.',
      price: 100.0,
      stock: 80,
      category_id: 5,
      seller_id: 1,
    },
    {
      name: 'Boné',
      description: 'Boné ajustável.',
      price: 30.0,
      stock: 120,
      category_id: 5,
      seller_id: 1,
    },
    {
      name: 'Boneca',
      description: 'Boneca de pano.',
      price: 40.0,
      stock: 100,
      category_id: 6,
      seller_id: 1,
    },
    {
      name: 'Carrinho de Brinquedo',
      description: 'Carrinho de brinquedo de metal.',
      price: 25.0,
      stock: 150,
      category_id: 6,
      seller_id: 1,
    },
    {
      name: 'Quebra-Cabeça',
      description: 'Quebra-cabeça de 1000 peças.',
      price: 50.0,
      stock: 60,
      category_id: 6,
      seller_id: 1,
    },
    {
      name: 'Caderno',
      description: 'Caderno universitário.',
      price: 20.0,
      stock: 200,
      category_id: 7,
      seller_id: 1,
    },
    {
      name: 'Caneta',
      description: 'Caneta esferográfica azul.',
      price: 2.0,
      stock: 300,
      category_id: 7,
      seller_id: 1,
    },
    {
      name: 'Mochila Escolar',
      description: 'Mochila para estudantes.',
      price: 80.0,
      stock: 50,
      category_id: 7,
      seller_id: 1,
    },
    {
      name: 'Pneu',
      description: 'Pneu para carro.',
      price: 300.0,
      stock: 50,
      category_id: 8,
      seller_id: 1,
    },
    {
      name: 'Óleo de Motor',
      description: 'Óleo lubrificante para motor.',
      price: 30.0,
      stock: 100,
      category_id: 8,
      seller_id: 1,
    },
    {
      name: 'Bateria de Carro',
      description: 'Bateria de carro 60Ah.',
      price: 400.0,
      stock: 30,
      category_id: 8,
      seller_id: 1,
    },
    {
      name: 'Sofá',
      description: 'Sofá de 3 lugares.',
      price: 1500.0,
      stock: 20,
      category_id: 9,
      seller_id: 1,
    },
    {
      name: 'Mesa de Jantar',
      description: 'Mesa de jantar para 6 pessoas.',
      price: 1000.0,
      stock: 15,
      category_id: 9,
      seller_id: 1,
    },
    {
      name: 'Cadeira de Escritório',
      description: 'Cadeira ergonômica para escritório.',
      price: 600.0,
      stock: 25,
      category_id: 9,
      seller_id: 1,
    },
    {
      name: 'Pá de Jardim',
      description: 'Pá de metal para jardinagem.',
      price: 25.0,
      stock: 50,
      category_id: 10,
      seller_id: 1,
    },
    {
      name: 'Vaso de Planta',
      description: 'Vaso de plástico para plantas.',
      price: 15.0,
      stock: 80,
      category_id: 10,
      seller_id: 1,
    },
    {
      name: 'Mangueira',
      description: 'Mangueira de jardim 20 metros.',
      price: 50.0,
      stock: 40,
      category_id: 10,
      seller_id: 1,
    },
    {
      name: 'Ração para Cães',
      description: 'Ração premium para cães adultos.',
      price: 120.0,
      stock: 100,
      category_id: 11,
      seller_id: 1,
    },
    {
      name: 'Brinquedo para Gatos',
      description: 'Brinquedo interativo para gatos.',
      price: 30.0,
      stock: 150,
      category_id: 11,
      seller_id: 1,
    },
    {
      name: 'Caixa de Transporte',
      description: 'Caixa de transporte para pets.',
      price: 150.0,
      stock: 60,
      category_id: 11,
      seller_id: 1,
    },
  ],
];
